import { NextRequest } from "next/server";
import archiver from "archiver";
import { PassThrough } from "stream";

export const runtime = "nodejs";

interface ExportBody {
  html: string;
  title: string;
}

// ── Next.js project template files ──

const packageJson = (title: string) =>
  JSON.stringify(
    {
      name: toSlug(title),
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
      },
      dependencies: {
        next: "^15",
        react: "^19",
        "react-dom": "^19",
      },
      devDependencies: {
        "@types/node": "^22",
        "@types/react": "^19",
        "@types/react-dom": "^19",
        typescript: "^5",
        "@tailwindcss/postcss": "^4",
        tailwindcss: "^4",
      },
    },
    null,
    2,
  );

const tsconfig = JSON.stringify(
  {
    compilerOptions: {
      target: "ES2017",
      lib: ["dom", "dom.iterable", "esnext"],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: "esnext",
      moduleResolution: "bundler",
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: "preserve",
      incremental: true,
      plugins: [{ name: "next" }],
      paths: { "@/*": ["./src/*"] },
    },
    include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
    exclude: ["node_modules"],
  },
  null,
  2,
);

const nextConfig = `/** @type {import('next').NextConfig} */
const nextConfig = {};
export default nextConfig;
`;

const postcssConfig = `const config = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};
export default config;
`;

const globalsCss = `@import "tailwindcss";
`;

function layoutTsx(title: string) {
  return `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: ${JSON.stringify(title)},
  description: "Generated by Agent Arena",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
`;
}

function pageTsx(html: string) {
  // Escape backticks and ${} in the HTML for template literal safety
  const escaped = html
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");

  return `export default function Home() {
  return (
    <div
      dangerouslySetInnerHTML={{
        __html: \`${escaped}\`,
      }}
    />
  );
}
`;
}

const readme = (title: string) => `# ${title}

Generated by [Agent Arena](https://github.com/wigtn/wigent) — AI 에이전트 토론 플랫폼

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000).
`;

function toSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9가-힣\s-]/g, "")
    .replace(/\s+/g, "-")
    .slice(0, 50)
    || "landing-page";
}

export async function POST(req: NextRequest) {
  let body: ExportBody;
  try {
    body = await req.json();
  } catch {
    return Response.json(
      { error: "Invalid JSON" },
      { status: 400 },
    );
  }

  const { html, title } = body;
  if (!html || !title) {
    return Response.json(
      { error: "html and title are required" },
      { status: 400 },
    );
  }

  const slug = toSlug(title);
  const prefix = `${slug}/`;

  // Create zip via archiver → PassThrough → ReadableStream
  const passthrough = new PassThrough();
  const archive = archiver("zip", { zlib: { level: 9 } });
  archive.pipe(passthrough);

  // Add project files
  archive.append(packageJson(title), { name: `${prefix}package.json` });
  archive.append(tsconfig, { name: `${prefix}tsconfig.json` });
  archive.append(nextConfig, { name: `${prefix}next.config.mjs` });
  archive.append(postcssConfig, { name: `${prefix}postcss.config.mjs` });
  archive.append(readme(title), { name: `${prefix}README.md` });
  archive.append(globalsCss, { name: `${prefix}src/app/globals.css` });
  archive.append(layoutTsx(title), { name: `${prefix}src/app/layout.tsx` });
  archive.append(pageTsx(html), { name: `${prefix}src/app/page.tsx` });
  archive.append(".next\nnode_modules\n", { name: `${prefix}.gitignore` });

  archive.finalize();

  // Convert Node stream to Web ReadableStream
  const readable = new ReadableStream({
    start(controller) {
      passthrough.on("data", (chunk: Buffer) => controller.enqueue(chunk));
      passthrough.on("end", () => controller.close());
      passthrough.on("error", (err) => controller.error(err));
    },
  });

  return new Response(readable, {
    headers: {
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="${slug}.zip"`,
    },
  });
}
